languageCode = "en"
languageName = "English"
weight = 15
title = "Raúl Coterillo"

[params]
  displayName = "🇬🇧 English"
  isoCode = "en-US"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Raúl Coterillo"
  image = "img/profile.jpeg"
  headline = "PhD student in theoretical neuroscience"
  # bio = "A little bit about you"
  links = [
      { email = "mailto:raulcote98@mailbox.org" },
      { x-twitter = "https://twitter.com/rcoteru" },
      { instagram = "https://instagram.com/rcoteru" },
      { goodreads = "https://goodreads.com/rcoteru" },
      { github = "https://github.com/rcoteru" },
      { linkedin = "https://www.linkedin.com/in/raul-coterillo/" },
      { orcid = "https://orcid.org/0000-0001-7567-3646" },
      { google = "https://scholar.google.es/citations?user=EmdWp8kAAAAJ&hl=es" },
  ]
